package com.ptit.itjob.model;
// Generated Nov 11, 2017 10:15:30 AM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "job", catalog = "itjob")
public class Job implements java.io.Serializable {

	private Integer id;
	private Company company;
	private Experience experience;
	private Location locationByJobtypeId;
	private Location locationByLocationId;
	private String title;
	private double salary;
	private String description;
	private String requirement;
	private Date createdAt;
	private Set<Skill> skills = new HashSet<Skill>(0);

	public Job() {
	}

	public Job(Company company, Experience experience, Location locationByJobtypeId, Location locationByLocationId,
			String title, double salary, String description, String requirement, Date createdAt) {
		this.company = company;
		this.experience = experience;
		this.locationByJobtypeId = locationByJobtypeId;
		this.locationByLocationId = locationByLocationId;
		this.title = title;
		this.salary = salary;
		this.description = description;
		this.requirement = requirement;
		this.createdAt = createdAt;
	}

	public Job(Company company, Experience experience, Location locationByJobtypeId, Location locationByLocationId,
			String title, double salary, String description, String requirement, Date createdAt, Set<Skill> skills) {
		this.company = company;
		this.experience = experience;
		this.locationByJobtypeId = locationByJobtypeId;
		this.locationByLocationId = locationByLocationId;
		this.title = title;
		this.salary = salary;
		this.description = description;
		this.requirement = requirement;
		this.createdAt = createdAt;
		this.skills = skills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "experience_id", nullable = false)
	public Experience getExperience() {
		return this.experience;
	}

	public void setExperience(Experience experience) {
		this.experience = experience;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobtype_id", nullable = false)
	public Location getLocationByJobtypeId() {
		return this.locationByJobtypeId;
	}

	public void setLocationByJobtypeId(Location locationByJobtypeId) {
		this.locationByJobtypeId = locationByJobtypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id", nullable = false)
	public Location getLocationByLocationId() {
		return this.locationByLocationId;
	}

	public void setLocationByLocationId(Location locationByLocationId) {
		this.locationByLocationId = locationByLocationId;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "salary", nullable = false, precision = 22, scale = 0)
	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "requirement", nullable = false, length = 1000)
	public String getRequirement() {
		return this.requirement;
	}

	public void setRequirement(String requirement) {
		this.requirement = requirement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "jobskill", catalog = "itjob", joinColumns = {
			@JoinColumn(name = "job_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "skill_id", nullable = false, updatable = false) })
	public Set<Skill> getSkills() {
		return this.skills;
	}

	public void setSkills(Set<Skill> skills) {
		this.skills = skills;
	}

}
