package com.ptit.itjob.model;
// Generated Nov 11, 2017 10:15:30 AM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jobtype generated by hbm2java
 */
@Entity
@Table(name = "jobtype", catalog = "itjob")
public class Jobtype implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Candidate> candidates = new HashSet<Candidate>(0);

	public Jobtype() {
	}

	public Jobtype(String name, Set<Candidate> candidates) {
		this.name = name;
		this.candidates = candidates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobtype")
	public Set<Candidate> getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set<Candidate> candidates) {
		this.candidates = candidates;
	}

}
